
# Giới thiệu github/workflows 
# Tệp này định nghĩa các công việc sẽ được thực hiện khi có sự kiện xảy ra trong kho lưu trữ.
# Trong trường hợp này, nó sẽ chạy khi có đẩy vào nhánh main hoặc develop, hoặc khi có yêu cầu kéo (pull request) được mở, đồng bộ hóa hoặc tái mở.

name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
